### ISSUE TITLE
Bug : Argument 1 passed to Austral\EntityFileBundle\File\Upload\FileUploader::uploadFile(), null given

### ISSUE THREAD

**Issue by clement-meunier** [austral-project/content-block-bundle#1]
### Error message : 
Argument 1 passed to Austral\EntityFileBundle\File\Upload\FileUploader::uploadFile() must be an instance of Austral\EntityFileBundle\File\Mapping\FieldFileMapping, null given, called in /home/www-data/vendor/content-block-bundle/Listener/FormListener.php on line 375

### How to reproduce :
Create a component with as block:
- image
- value (type text)

Add this new component in page and add image.

if the bloc "value" has option "has link" equal true, i've the bug.

**Comment by mbeurel** [comment]
It came from creating component with multi block include upload files;
Bug is fixed.
